 build:
9:59:55 PM:     command: npm run build
9:59:55 PM:     commandOrigin: config
9:59:55 PM:     publish: /opt/build/repo/public
9:59:55 PM:     publishOrigin: config
9:59:55 PM:   redirects:
9:59:55 PM:     - from: /*
      status: 200
      to: /index.html
    - conditions:
        Country:
          - US
        Language:
          - en
        Role:
          - admin
      from: /old-path
      query:
        path: ':path'
      status: 301
      to: /new-path
    - force: true
      from: /search
      headers:
        X-From: Netlify
      signed: API_SIGNATURE_TOKEN
      status: 200
      to: https://api.mysearch.com
  redirectsOrigin: config
Caching artifacts